INSERT INTO PLAYER(BALANCE) VALUES(600.00);
INSERT INTO PLAYER(BALANCE) VALUES(1300.00);
INSERT INTO PLAYER(BALANCE) VALUES(1100.00);
INSERT INTO PLAYER(BALANCE) VALUES(3500.00);
INSERT INTO PLAYER(BALANCE) VALUES(7000.00);
INSERT INTO PLAYER(BALANCE) VALUES(80.43);
INSERT INTO PLAYER(BALANCE) VALUES(1700.00);
INSERT INTO PLAYER(BALANCE) VALUES(850.78);
INSERT INTO PLAYER(BALANCE) VALUES(300.00);
INSERT INTO PLAYER(BALANCE) VALUES(500.00);


INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(1,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(2,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(3,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(4,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(5,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(6,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(7,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(8,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(9,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(10,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(11,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(12,'DEDUCT',100.00,1,sysdate());

INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(13,'DEPOSIT',200.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(14,'DEPOSIT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(15,'DEPOSIT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(16,'DEDUCT',500.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(17,'DEDUCT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(18,'DEDUCT',100.00,3,sysdate());