INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(600.00,'Mpholo','Leboea','mpholo.leboea@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(1300.00,'Tebogo','Kgofelo','tebogo@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(1100.00,'Linda','Keke','linda@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(3500.00,'moseki','kgadiwaphukwi','moseki@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(7000.00,'sam','banda','sam@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(80.43,'boitumelo','lee','lee@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(1700.00,'japi','music','japi@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(850.78,'morena','mang','mang@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(300.00,'jakes','senokwane','jakeas@gmail.com');
INSERT INTO PLAYER(BALANCE,FIRST_NAME,LAST_NAME,EMAIL) VALUES(500.00,'hello','man','hello.man@gmail.com');


INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(1,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(2,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(3,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(4,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(5,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(6,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(7,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(8,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(9,'DEPOSIT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(10,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(11,'DEDUCT',100.00,1,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(12,'DEDUCT',100.00,1,sysdate());

INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(13,'DEPOSIT',200.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(14,'DEPOSIT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(15,'DEPOSIT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(16,'DEDUCT',500.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(17,'DEDUCT',100.00,3,sysdate());
INSERT INTO TRANSACTION(TRANSACTION_ID,TYPE,AMOUNT,PLAYER_ID,CREATION_DATE) VALUES(18,'DEDUCT',100.00,3,sysdate());