INSERT INTO PLAYER(BALANCE) VALUES(600.00);
INSERT INTO PLAYER(BALANCE) VALUES(1300.00);
INSERT INTO PLAYER(BALANCE) VALUES(1100.00);
INSERT INTO PLAYER(BALANCE) VALUES(3500.00);
INSERT INTO PLAYER(BALANCE) VALUES(7000.00);
INSERT INTO PLAYER(BALANCE) VALUES(80.43);
INSERT INTO PLAYER(BALANCE) VALUES(1700.00);
INSERT INTO PLAYER(BALANCE) VALUES(850.78);
INSERT INTO PLAYER(BALANCE) VALUES(300.00);
INSERT INTO PLAYER(BALANCE) VALUES(500.00);


INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',100.00,1);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',100.00,1);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',100.00,1);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',100.00,1);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',100.00,1);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',100.00,1);

INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',200.00,3);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',100.00,3);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEPOSIT',100.00,3);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',500.00,3);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',100.00,3);
INSERT INTO TRANSACTION(TYPE,AMOUNT,PLAYER_ID) VALUES('DEDUCT',100.00,3);